FROM taigaio/taiga-back:6.8.1

COPY --chown=taiga:taiga ./back /tmp/taiga-contrib-oidc-auth
RUN pip install /tmp/taiga-contrib-oidc-auth && \
    rm -rf /tmp/taiga-contrib-oidc-auth

COPY --chown=taiga:taiga ./config.snippet.py ./urls.py /taiga-back/settings/
RUN cat /taiga-back/settings/config.snippet.py >> /taiga-back/settings/config.py
