name: Docker Image CI

on:
  push:
    branches:
      - add-group
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - add-group

jobs:
  build:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: add-group

      - name: Docker meta backend image
        id: meta-back
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/untitledds/taiga-back
          flavor: |
            suffix=-oidc
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'add-group' }}
            type=semver,pattern={{raw}}
            type=ref,event=pr

      - name: Docker meta frontend image
        id: meta-front
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/untitledds/taiga-front
          flavor: |
            suffix=-oidc
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'add-group' }}
            type=semver,pattern={{raw}}
            type=ref,event=pr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.back
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta-back.outputs.tags }}
          platforms: linux/amd64

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.front
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta-front.outputs.tags }}
          platforms: linux/amd64

      - name: Build and push dev backend image
        if: github.ref_type != 'tag'
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.back
          push: true
          tags: ghcr.io/untitledds/taiga-back:dev
          platforms: linux/amd64

      - name: Build and push dev frontend image
        if: github.ref_type != 'tag'
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.front
          push: true
          tags: ghcr.io/untitledds/taiga-front:dev
          platforms: linux/amd64
